### ISSUE TITLE
rm::test_rm_rm3 test fails on Ubuntu LTS 22.04

### ISSUE THREAD

**Issue by jgarzik** [rustcoreutils/posixutils-rs#118]
Commit 3c329054d2353823361d435a48848a41c6b89cef with recent fixes still fails on Ubuntu/Linux:
```
failures:

---- rm::test_rm_rm3 stdout ----
thread 'rm::test_rm_rm3' panicked at tree/tests/rm/mod.rs:897:9:
assertion `left == right` failed
  left: ["", "rm: descend into directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/d'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/du'", "rm: remove regular empty file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/empty'", "rm: remove regular empty file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/empty-u'", "rm: remove regular file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/fu'", "rm: remove symbolic link '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/slink'", "rm: remove symbolic link '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/slinkdot'"]
 right: ["", "rm: descend into directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/d'", "rm: remove regular empty file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/empty'", "rm: remove symbolic link '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/slink'", "rm: remove symbolic link '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/slinkdot'", "rm: remove write-protected directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/du'", "rm: remove write-protected regular empty file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/empty-u'", "rm: remove write-protected regular file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/fu'"]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    rm::test_rm_rm3

test result: FAILED. 87 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out; finished in 3.04s

error: test failed, to rerun pass `-p posixutils-tree --test integration`
```

**Comment by JRF63** [comment]
Can I ask if:
a) the errors intermittent and,
b) if it still give errors if `test_rm_rm3` is run by itself?

**Comment by jgarzik** [comment]
> Can I ask if: a) the errors are intermittent and, b) if it still give errors if `test_rm_rm3` is run by itself?

a) No, test_rm_rm3 fails every time.

b) it still fails, if run by itself and no other tests have been run (`cargo clean`):
```
$ cargo test -p posixutils-tree --test integration rm::test_rm_rm3 -- --nocapture
   Compiling posixutils-tree v0.1.10 (/home/jgarzik/repo/posixutils-rs/tree)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 1.22s
     Running tests/integration.rs (target/debug/deps/integration-8e3522adf16a856c)

running 1 test
thread 'rm::test_rm_rm3' panicked at tree/tests/rm/mod.rs:897:9:
assertion `left == right` failed
  left: ["", "rm: descend into directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/d'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/du'", "rm: remove regular empty file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/empty'", "rm: remove regular empty file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/empty-u'", "rm: remove regular file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/fu'", "rm: remove symbolic link '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/slink'", "rm: remove symbolic link '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/slinkdot'"]
 right: ["", "rm: descend into directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z'", "rm: remove directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/d'", "rm: remove regular empty file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/empty'", "rm: remove symbolic link '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/slink'", "rm: remove symbolic link '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/slinkdot'", "rm: remove write-protected directory '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/du'", "rm: remove write-protected regular empty file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/empty-u'", "rm: remove write-protected regular file '/home/jgarzik/repo/posixutils-rs/target/tmp/test_rm_rm3/z/fu'"]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test rm::test_rm_rm3 ... FAILED

failures:

failures:
    rm::test_rm_rm3

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 93 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p posixutils-tree --test integration`
```

**Comment by jgarzik** [comment]
The Linux machine where this fails has a default shell umask of 0002.

Further data point:
The test succeeds if the current process umask is `022`.  
The test fails if the current process umask is `0002`.

Definitely umask related, it seems.
