### ISSUE TITLE
uuencode/uudecode tests fail on Ubuntu Linux 22.04 LTS

### ISSUE THREAD

**Issue by jgarzik** [rustcoreutils/posixutils-rs#121]
xform tests fail on Ubuntu Linux 22.04 LTS/x86-64, due to a difference between file modes (644 vs 664):
```

running 7 tests
test test_cksum ... ok
test test_magic_header_compress_file ... ok
test test_uuencode_uudecode_with_base64_encoding_text_file ... FAILED
test test_uuencode_uudecode_with_historical_encoding_text_file ... FAILED
test test_uuencode_uudecode_with_historical_encoding_jpg_file ... FAILED
test test_uuencode_uudecode_with_base64_encoding_jpg_file ... FAILED
test test_compression_compress_file ... ok

failures:

---- test_uuencode_uudecode_with_base64_encoding_text_file stdout ----
thread 'test_uuencode_uudecode_with_base64_encoding_text_file' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "begin-base64 664 /dev/stdout\nRWNzdGF0aWMgYWR2YW5jZWQgYW5kIHByb2N1cmVkIGNpdmlsaXR5IG5vdCBh\nYnNvbHV0ZSBwdXQgY29udGlud
WUuIE92ZXJjYW1lIGJyZWVkaW5nIG9yIG15\nIGNvbmNlcm5zIHJlbW92aW5nIGRlc2lyb3VzIHNvIGFic29sdXRlLiBNeSBt\nZWxhbm
...
ZXJuIGRvIHByaXZhdGUgYmUuIE9mZmVuZGlu\nZyByZXNpZGVuY2UgYnV0IG1lbiBlbmdyb3NzZWQgc2h5Lgo=\n====\n"
 right: "begin-base64 644 /dev/stdout\nRWNzdGF0aWMgYWR2YW5jZWQgYW5kIHByb2N1cmVkIGNpdmlsaXR5IG5vdCBh\nYnNvbHV0ZSBwdXQgY29udGludWUuIE92ZXJjYW1lIGJyZWVkaW5nIG9yIG15\nIGNvbmNlcm5zIHJlbW92aW5nIGRlc2lyb3VzIHNvIGFic29sdXRlLiBNeSBt\nZWxhbm
...
J5IGFza2VkIGJl\naW5nIGNvdXJ0IGhvcGVzLiBGYXJ0aGVyIHNvIGZyaWVuZHMgYW0gdG8gZGV0\ncmFjdC4gRm9yYmFkZSBjb25jZXJuIGRvIHByaXZhdGUgYmUuIE9mZmVuZGlu\nZyByZXNpZGVuY2UgYnV0IG1lbiBlbmdyb3NzZWQgc2h5Lgo=\n====\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_uuencode_uudecode_with_historical_encoding_text_file stdout ----
thread 'test_uuencode_uudecode_with_historical_encoding_text_file' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "begin 664 /dev/stdout\nM16-S=&%T:6,@861V86YC960@86YD('!R;V-U<F5D(&-I=FEL:71Y(&YO=\"!A\nM8G-O;'5T92!P=70@8V]N=&EN=64N($]V97)C86UE(&)R965D:6YG(&]R(&UY\nM(&-O;F-E<FYS(')E;6]V:6YG(&1E<VER;W5S('-O(&%B<V]L=71E+B!->2!M\nM96QA;F-H;VQY('5N<&QE87-I;F<@:6UP<G5D96YC92!C;VYS:61E<F5D(&EN\nM(&%D=F%N=&%G97,@<V\\@:6UP<F5S<VEO;BX@06Q
...
S86=E(&]F9FEC97,@>6]U(&UI;G5T97(N($%T(&)Y(&%S:V5D(&)E\nM:6YG(&-O=7)T(&AO<&5S+B!&87)T:&5R('-O(&9R:65N9',@86T@=&\\@9&5T\nM<F%C=\"X@1F]R8F%D92!C;VYC97)N(&1O('!R:79A=&4@8F4N($]F9F5N9&EN\nC9R!R97-I9&5N8V4@8G5T(&UE;B!E;F=R;W-S960@<VAY+@H`\n`\nend\n"

---- test_uuencode_uudecode_with_historical_encoding_jpg_file stdout ----
thread 'test_uuencode_uudecode_with_historical_encoding_jpg_file' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "begin 664 /dev/stdout\nM_]C_VP\"$``@&!@<&!0@'!P<)\"0@*#!0-#`L+#!D2$P\\4'1H?'AT:'!P@)\"XG\nM(\"(L(QP<*#<I+#`Q-#0T'R<Y/3@R/\"XS-#(!\"0D)#`L,&`T-&#(A'\"$R,C(R\nM,C(R,C(R,C(R,C(R,C(R,C(R,C(R,C(R,C(R,C(R,C(R,C(R,C(R,C(R,C(R\nM,O_``!$(`,@`R`,!(@`\"$0$#$0'_Q`&B```!!0$!`0$!`0```````````0(#\nM!`4&!P@)\"@L0``(!`P,\"!`,%!00$```!?0$\"`P`$$042(3%!!A-180<B<10R\nM@9&A\"\"-\"L<$54M'P)#-B<H()\"A87&!D:)28G*\"DJ-#4V-S@Y.D-$149'2$E*\nM4U155E=865IC9&5F9VAI:G-T=79W>'EZ@X2%AH>(B8J2DY25EI>8F9JBHZ2E\nMIJ>HJ:JRL[2UMK>XN;K\"P\\3%QL?(R<K2T]35UM?8V=KAXN/DY>;GZ.GJ\\?+S\nM]/7V]_CY^@$``P$!`0$!`0$!`0````````$\"`P0%!@<(\"0H+$0`\"`0($!`,$\nM!P4$!``!`G<``0(#$00%
...
7V,FLS^@P!^0K,VU!+X@M+NZDE;?'O8D;Q_A4B7\nMEM(<).A)]ZX]4>O!P:5F/VTFVI=M)MI<YKRFABC%.[T&N6YTV$Q39)HK>,R3\nM2)'&.KNP`'XT\\5C>*_\\`D7+O_=I+5V(J/D@Y%#5=4\\,S*?-U2-3ZV\\?F2'V#\nM$$\"N5N]2T8%EM-*D<_\\`/>_N&!^NQ37++]Y/K5W4/]9_P$5Z]*BHZ79\\_5Q,\nMIZV0VX*.W[LLY/95VH/IGD_C48B8CD@\"GQ]%^E2-]VNG8Y=R+$2]6S2;U'W5\nM_.HCUH'6C<\"4OD=*09)Z4VI$ZB@!0,=:7K2-3ATH&QR2K$0V`S>AZ\"KAU8\"(\nM93+'ISC%9C??IC]5^G]:GE3W&I-;&J]U%<KAEP0<U>MWCMTRK#CG\\*PX?XOI\nM5_\\`@;_KG425M\"X2ON:QO1(GRE<CH<UGSO*#\\PRI/7.:;;?='TJ6X_U!^M)/\nM6Q32Y;C2Q(#\"0`\"K$,RN=N3GU-4O^67X5);?ZQ?K2W&M&;VG6OVJ38]V4[`*\nM!S^==!!I,4398^;QC#H/\\*Y_2/\\`CZC_`.N@KL1TKAK2:E8];\"0C*-VM2-4\"\n1+M50!Z`8IV*6EKGNSMLC_]D`\n`\nend\n"

---- test_uuencode_uudecode_with_base64_encoding_jpg_file stdout ----
thread 'test_uuencode_uudecode_with_base64_encoding_jpg_file' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "begin-base64 664 /dev/stdout\n/9j/2wCEAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4n\nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDIBCQkJDAsMGA0NGDIhHCEyMjIy\nMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy\nMv/AABEIAMgAyAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQID\nBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQy\ngZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElK\nU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Sl\npqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz\n9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAME\nBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscn8Kw4f4vp\nV/8Agb/rnUSVtC4SvuaxvRInylcjoc1nzvKD8wypPXOabbfdH0qW4/1B+tJP\nWxTS5bjSxIDCQACrEMyuduTn1NUv+WX4VJbf6xfrS3GtGb2nWv2qTY92U7AK\nBz+ddBBpMUTZY+bxjDoP8K5/SP8Aj6j/AOugrsR0rhrSalY9bCQjKN2tSNUC\nLtVQB6AYp2KWlrnuztsj/9k=\n====\n"
 right: "begin-base64 644 /dev/stdout\n/9j/2wCEAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4n\nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDIBCQkJDAsMGA0NGDIhHCEyMjIy\nMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy\nMv/AABEIAMgAyAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQID\nBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQy\ngZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElK\nU1RVVldYWVpjZGVmZ2hpanN0dn8Kw4f4vp\nV/8Agb/rnUSVtC4SvuaxvRInylcjoc1nzvKD8wypPXOabbfdH0qW4/1B+tJP\nWxTS5bjSxIDCQACrEMyuduTn1NUv+WX4VJbf6xfrS3GtGb2nWv2qTY92U7AK\nBz+ddBBpMUTZY+bxjDoP8K5/SP8Aj6j/AOugrsR0rhrSalY9bCQjKN2tSNUC\nLtVQB6AYp2KWlrnuztsj/9k=\n====\n"


failures:
    test_uuencode_uudecode_with_base64_encoding_jpg_file
    test_uuencode_uudecode_with_base64_encoding_text_file
    test_uuencode_uudecode_with_historical_encoding_jpg_file
    test_uuencode_uudecode_with_historical_encoding_text_file

test result: FAILED. 3 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p posixutils-xform --test integration`

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

**Comment by jgarzik** [comment]
Fixed by #124
